### ISSUE TITLE
publish fail

### ISSUE THREAD

**Issue by oshai** [MicroUtils/kotlin-logging#213]
https://github.com/MicroUtils/kotlin-logging/runs/4537658897?check_suite_focus=true
error is:
```
> Task :closeSonatypeStagingRepository FAILED
FAILURE: Build failed with an exception.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
* What went wrong:

Execution failed for task ':closeSonatypeStagingRepository'.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> Staging repository is still transitioning after defined time. Consider its increment. StagingRepository(id=iogithubmicroutils-1132, state=open, transitioning=true)


See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
* Try:

Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Execution optimizations have been disabled for 10 invalid unit(s) of work during this build to ensure correctness.

Please consult deprecation warnings for more details.
* Exception is:
62 actionable tasks: 62 executed
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':closeSonatypeStagingRepository'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:188)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:186)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:174)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecu
```

**Comment by oshai** [comment]
trying to revert #209

**Comment by severn-everett** [comment]
What does the normal output of the `Publish` task look like?

**Comment by oshai** [comment]
Normal publish looks like this: https://github.com/MicroUtils/kotlin-logging/runs/4491939685?check_suite_focus=true

I am trying to revert commits to triage it.

**Comment by oshai** [comment]
I see that sonatype are doing maintanance now:
```
Caused by: java.lang.RuntimeException: Failed to load staging profiles, server at https://oss.sonatype.org/service/local/ responded with status code 405, body: Method not allowed during maintenance
```

**Comment by severn-everett** [comment]
Welp, that's not helpful. Also, they should be returning a 409(or maybe
423) for a "temporarily unavailable endpoint" error, not a 405.

**Comment by oshai** [comment]
I release now 2.1.17 from earlier today (the first one):
![image](https://user-images.githubusercontent.com/2683969/146274168-df306d7b-870d-4a97-914c-e17453723d45.png)

**Comment by oshai** [comment]
2.1.17 contains all fixes from today.
I will later try to release 2.1.20 (no changes).
